### ISSUE TITLE
Testy issue

### ISSUE THREAD

**Issue by Antonimo** [Nekudapsik/GulpStarter#3]
![54565e3faf097image](https://cloud.githubusercontent.com/assets/612902/4876109/1b04bef0-62b6-11e4-9f05-7ca1dc046d5f.png)

huina 

![54565e14b9eddimage](https://cloud.githubusercontent.com/assets/612902/4876112/35082f1c-62b6-11e4-8d53-5644ca7f13a2.png)

**Comment by Antonimo** [comment]
TESTY TEST 2

**Comment by Nekudapsik** [comment]
Duplicate of #2
